### ISSUE TITLE
确认服务器支持多于20根的line

### ISSUE THREAD

**Issue by leohca** [gamesmama/game-docs#5]
目前设置大于20则游戏不停止滚动，需要确认服务器支持大于20 的设置![Image](https://github.com/user-attachments/assets/f34fdd03-0800-4850-bbd4-0a016e13c8be)

**Comment by beforeProspective** [comment]
支持设置>20的
需要修改\packages\game-multi-slots\src\Http\Requests\Frontend\PlayGame.php文件的![Image](https://github.com/user-attachments/assets/c64e7332-bcc2-4052-8706-8e7363e1a38c)
去掉max:20的限制
再在\packages\game-multi-slots\src\Services\GameMultiSlotsService.php文件的![Image](https://github.com/user-attachments/assets/ee5b7791-2ab8-49d2-8763-1e7a6757e084)
里面添加对应线的规则
